package com.example.workout.workout.mapper;

import com.example.workout.generated.model.WorkoutCreateRequest;
import com.example.workout.generated.model.WorkoutLapResponse;
import com.example.workout.generated.model.WorkoutResponse;
import com.example.workout.generated.model.WorkoutSegmentResponse;
import com.example.workout.generated.model.WorkoutSummaryResponse;
import com.example.workout.generated.model.WorkoutTrackPointResponse;
import com.example.workout.workout.model.Workout;
import com.example.workout.workout.model.WorkoutFeeling;
import com.example.workout.workout.model.WorkoutSource;
import com.example.workout.workout.model.WorkoutType;

public final class WorkoutMapper {
    private WorkoutMapper() { throw new UnsupportedOperationException("This class should never be instantiated"); }
    public static Workout fromCreateDto(WorkoutCreateRequest dto) {
        Workout workout = new Workout(); workout.setWorkoutDate(dto.getWorkoutDate()); workout.setName(dto.getName()); workout.setWorkoutType(WorkoutType.valueOf(dto.getWorkoutType().getValue())); workout.setDescription(dto.getDescription()); workout.setNotes(dto.getNotes()); workout.setDistanceMeters(dto.getDistanceMeters()); workout.setDurationSeconds(dto.getDurationSeconds()); workout.setMovingTimeSeconds(dto.getMovingTimeSeconds()); workout.setAveragePaceSecondsPerKm(dto.getAveragePaceSecondsPerKm()); workout.setBestPaceSecondsPerKm(dto.getBestPaceSecondsPerKm()); workout.setAverageHeartRate(dto.getAverageHeartRate()); workout.setMaxHeartRate(dto.getMaxHeartRate()); workout.setAverageCadence(dto.getAverageCadence()); workout.setMaxCadence(dto.getMaxCadence()); workout.setAveragePowerWatts(dto.getAveragePowerWatts()); workout.setMaxPowerWatts(dto.getMaxPowerWatts()); workout.setElevationGainMeters(dto.getElevationGainMeters()); workout.setElevationLossMeters(dto.getElevationLossMeters()); workout.setMinimumElevationMeters(dto.getMinimumElevationMeters()); workout.setMaximumElevationMeters(dto.getMaximumElevationMeters()); workout.setCalories(dto.getCalories()); workout.setAverageStrideLengthMeters(dto.getAverageStrideLengthMeters()); workout.setVerticalOscillationCm(dto.getVerticalOscillationCm()); workout.setGroundContactTimeMs(dto.getGroundContactTimeMs()); workout.setPerceivedEffort(dto.getPerceivedEffort()); if (dto.getFeeling()!=null) workout.setFeeling(WorkoutFeeling.valueOf(dto.getFeeling().getValue())); workout.setCompleted(dto.getCompleted()); workout.setTemperatureCelsius(dto.getTemperatureCelsius()); workout.setHumidityPercent(dto.getHumidityPercent()); workout.setWindSpeedKph(dto.getWindSpeedKph()); workout.setWeather(dto.getWeather()); workout.setLocation(dto.getLocation()); workout.setRouteName(dto.getRouteName()); workout.setSource(WorkoutSource.valueOf(dto.getSource().getValue())); workout.setExternalActivityId(dto.getExternalActivityId()); workout.setShoeId(dto.getShoeId()); if(dto.getSegments()!=null)dto.getSegments().forEach(x->workout.getSegments().add(WorkoutMapperAccess.segment(x))); if(dto.getLaps()!=null)dto.getLaps().forEach(x->workout.getLaps().add(WorkoutMapperAccess.lap(x))); if(dto.getTrackPoints()!=null)dto.getTrackPoints().forEach(x->workout.getTrackPoints().add(WorkoutMapperAccess.point(x))); return workout;
    }
    public static WorkoutResponse toDto(Workout w){WorkoutResponse d=new WorkoutResponse(); d.setId(w.getId());d.setWorkoutDate(w.getWorkoutDate());d.setName(w.getName());d.setWorkoutType(com.example.workout.generated.model.WorkoutType.fromValue(w.getWorkoutType().name()));d.setDescription(w.getDescription());d.setNotes(w.getNotes());d.setDistanceMeters(w.getDistanceMeters());d.setDurationSeconds(w.getDurationSeconds());d.setMovingTimeSeconds(w.getMovingTimeSeconds());d.setAveragePaceSecondsPerKm(w.getAveragePaceSecondsPerKm());d.setBestPaceSecondsPerKm(w.getBestPaceSecondsPerKm());d.setAverageHeartRate(w.getAverageHeartRate());d.setMaxHeartRate(w.getMaxHeartRate());d.setAverageCadence(w.getAverageCadence());d.setMaxCadence(w.getMaxCadence());d.setAveragePowerWatts(w.getAveragePowerWatts());d.setMaxPowerWatts(w.getMaxPowerWatts());d.setElevationGainMeters(w.getElevationGainMeters());d.setElevationLossMeters(w.getElevationLossMeters());d.setMinimumElevationMeters(w.getMinimumElevationMeters());d.setMaximumElevationMeters(w.getMaximumElevationMeters());d.setCalories(w.getCalories());d.setAverageStrideLengthMeters(w.getAverageStrideLengthMeters());d.setVerticalOscillationCm(w.getVerticalOscillationCm());d.setGroundContactTimeMs(w.getGroundContactTimeMs());d.setPerceivedEffort(w.getPerceivedEffort());if(w.getFeeling()!=null)d.setFeeling(com.example.workout.generated.model.WorkoutFeeling.fromValue(w.getFeeling().name()));d.setCompleted(w.getCompleted());d.setTemperatureCelsius(w.getTemperatureCelsius());d.setHumidityPercent(w.getHumidityPercent());d.setWindSpeedKph(w.getWindSpeedKph());d.setWeather(w.getWeather());d.setLocation(w.getLocation());d.setRouteName(w.getRouteName());d.setSource(com.example.workout.generated.model.WorkoutSource.fromValue(w.getSource().name()));d.setExternalActivityId(w.getExternalActivityId());d.setShoeId(w.getShoeId());d.setCreatedAt(w.getCreatedAt());d.setUpdatedAt(w.getUpdatedAt());d.setSegments(w.getSegments().stream().map(WorkoutMapper::segmentDto).toList());d.setLaps(w.getLaps().stream().map(WorkoutMapper::lapDto).toList());d.setTrackPoints(w.getTrackPoints().stream().map(WorkoutMapper::pointDto).toList());return d;}
    public static WorkoutSummaryResponse toSummaryDto(Workout w){WorkoutSummaryResponse d=new WorkoutSummaryResponse();d.setId(w.getId());d.setWorkoutDate(w.getWorkoutDate());d.setName(w.getName());d.setWorkoutType(com.example.workout.generated.model.WorkoutType.fromValue(w.getWorkoutType().name()));d.setDistanceMeters(w.getDistanceMeters());d.setDurationSeconds(w.getDurationSeconds());d.setCompleted(w.getCompleted());d.setSource(com.example.workout.generated.model.WorkoutSource.fromValue(w.getSource().name()));d.setShoeId(w.getShoeId());d.setCreatedAt(w.getCreatedAt());d.setUpdatedAt(w.getUpdatedAt());return d;}
    private static WorkoutSegmentResponse segmentDto(com.example.workout.workout.model.WorkoutSegment s){WorkoutSegmentResponse d=new WorkoutSegmentResponse();d.setId(s.getId());d.setPosition(s.getPosition());d.setSegmentType(com.example.workout.generated.model.WorkoutSegmentType.fromValue(s.getSegmentType().name()));d.setName(s.getName());d.setRepetitions(s.getRepetitions());d.setDistanceMeters(s.getDistanceMeters());d.setDurationSeconds(s.getDurationSeconds());d.setTargetPaceSecondsPerKm(s.getTargetPaceSecondsPerKm());d.setActualPaceSecondsPerKm(s.getActualPaceSecondsPerKm());d.setRestDistanceMeters(s.getRestDistanceMeters());d.setRestDurationSeconds(s.getRestDurationSeconds());d.setAverageHeartRate(s.getAverageHeartRate());d.setMaxHeartRate(s.getMaxHeartRate());d.setAverageCadence(s.getAverageCadence());d.setAveragePowerWatts(s.getAveragePowerWatts());d.setElevationGainMeters(s.getElevationGainMeters());d.setDescription(s.getDescription());return d;}
    private static WorkoutLapResponse lapDto(com.example.workout.workout.model.WorkoutLap l){WorkoutLapResponse d=new WorkoutLapResponse();d.setId(l.getId());d.setPosition(l.getPosition());d.setDistanceMeters(l.getDistanceMeters());d.setDurationSeconds(l.getDurationSeconds());d.setPaceSecondsPerKm(l.getPaceSecondsPerKm());d.setAverageHeartRate(l.getAverageHeartRate());d.setMaxHeartRate(l.getMaxHeartRate());d.setAverageCadence(l.getAverageCadence());d.setAveragePowerWatts(l.getAveragePowerWatts());d.setElevationGainMeters(l.getElevationGainMeters());d.setElevationLossMeters(l.getElevationLossMeters());return d;}
    private static WorkoutTrackPointResponse pointDto(com.example.workout.workout.model.WorkoutTrackPoint p){WorkoutTrackPointResponse d=new WorkoutTrackPointResponse();d.setId(p.getId());d.setPosition(p.getPosition());d.setRecordedAt(p.getRecordedAt());d.setLatitude(p.getLatitude());d.setLongitude(p.getLongitude());d.setElevationMeters(p.getElevationMeters());d.setHeartRate(p.getHeartRate());d.setCadence(p.getCadence());d.setPowerWatts(p.getPowerWatts());return d;}
}
