package com.example.workout.workout.entity;
import com.example.workout.workout.model.*; import jakarta.persistence.*; import java.math.BigDecimal; import java.time.*; import java.util.*; import lombok.*;
@Entity @Table(name="workouts") @Getter @Setter @NoArgsConstructor @AllArgsConstructor @Builder(setterPrefix="with")
public class WorkoutEntity {
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY) private Long id; @Column(name="workout_date",nullable=false) private LocalDate workoutDate; @Column(length=200) private String name; @Enumerated(EnumType.STRING) @Column(name="workout_type",nullable=false,length=30) private WorkoutType workoutType; @Column(length=2000) private String description; @Column(length=5000) private String notes;
 private Integer distanceMeters; private Integer durationSeconds; private Integer movingTimeSeconds; private Integer averagePaceSecondsPerKm; private Integer bestPaceSecondsPerKm; private Integer averageHeartRate; private Integer maxHeartRate; private Integer averageCadence; private Integer maxCadence; private Integer averagePowerWatts; private Integer maxPowerWatts; private Integer elevationGainMeters; private Integer elevationLossMeters; @Column(precision=10,scale=2) private BigDecimal minimumElevationMeters; @Column(precision=10,scale=2) private BigDecimal maximumElevationMeters; private Integer calories; @Column(precision=10,scale=3) private BigDecimal averageStrideLengthMeters; @Column(precision=10,scale=2) private BigDecimal verticalOscillationCm; private Integer groundContactTimeMs; private Integer perceivedEffort; @Enumerated(EnumType.STRING) @Column(length=20) private WorkoutFeeling feeling; @Column(nullable=false) private Boolean completed; @Column(precision=5,scale=2) private BigDecimal temperatureCelsius; private Integer humidityPercent; @Column(precision=8,scale=2) private BigDecimal windSpeedKph; @Column(length=100) private String weather; @Column(length=200) private String location; @Column(length=200) private String routeName; @Enumerated(EnumType.STRING) @Column(nullable=false,length=20) private WorkoutSource source; @Column(length=200) private String externalActivityId; private Long shoeId; @Column(nullable=false) private OffsetDateTime createdAt; @Column(nullable=false) private OffsetDateTime updatedAt;
 @OneToMany(mappedBy="workout",cascade=CascadeType.ALL,orphanRemoval=true) @OrderBy("position ASC") @Builder.Default private List<WorkoutSegmentEntity> segments=new ArrayList<>();
 @OneToMany(mappedBy="workout",cascade=CascadeType.ALL,orphanRemoval=true) @OrderBy("position ASC") @Builder.Default private List<WorkoutLapEntity> laps=new ArrayList<>();
 @OneToMany(mappedBy="workout",cascade=CascadeType.ALL,orphanRemoval=true) @OrderBy("position ASC") @Builder.Default private List<WorkoutTrackPointEntity> trackPoints=new ArrayList<>();
}
