package com.example.workout.workout.service;
import com.example.workout.common.exception.*; import com.example.workout.workout.entity.WorkoutEntity; import com.example.workout.workout.mapper.WorkoutEntityMapper; import com.example.workout.workout.model.*; import com.example.workout.workout.repository.WorkoutRepository; import jakarta.persistence.criteria.Predicate; import java.time.OffsetDateTime; import java.util.*; import lombok.RequiredArgsConstructor; import lombok.extern.slf4j.Slf4j; import org.springframework.data.domain.*; import org.springframework.data.jpa.domain.Specification; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @RequiredArgsConstructor @Slf4j @Transactional
public class WorkoutServiceImpl implements WorkoutService { private final WorkoutRepository repository;
 public Workout create(Workout workout){ validatePositions(workout); OffsetDateTime now=OffsetDateTime.now(); workout.setCreatedAt(now); workout.setUpdatedAt(now); WorkoutEntity saved=repository.save(WorkoutEntityMapper.toEntity(workout)); log.info("[WORKOUT] - ACTION: createWorkout: workoutId: {}",saved.getId()); return WorkoutEntityMapper.toModel(saved); }
 @Transactional(readOnly=true) public Workout get(Long id){ return WorkoutEntityMapper.toModel(find(id)); }
 @Transactional(readOnly=true) public Page<Workout> search(WorkoutFilter f, Pageable pageable){ Specification<WorkoutEntity> spec=(root,q,cb)->{ List<Predicate> p=new ArrayList<>(); if(f.workoutType()!=null)p.add(cb.equal(root.get("workoutType"),f.workoutType())); if(f.workoutDate()!=null)p.add(cb.equal(root.get("workoutDate"),f.workoutDate())); if(f.workoutDateFrom()!=null)p.add(cb.greaterThanOrEqualTo(root.get("workoutDate"),f.workoutDateFrom())); if(f.workoutDateTo()!=null)p.add(cb.lessThanOrEqualTo(root.get("workoutDate"),f.workoutDateTo())); if(f.completed()!=null)p.add(cb.equal(root.get("completed"),f.completed())); if(f.shoeId()!=null)p.add(cb.equal(root.get("shoeId"),f.shoeId())); if(f.source()!=null)p.add(cb.equal(root.get("source"),f.source())); return cb.and(p.toArray(Predicate[]::new));}; return repository.findAll(spec,pageable).map(WorkoutEntityMapper::toModel); }
 public Workout patch(Long id, Workout patch, WorkoutPatchPresence presence){ WorkoutEntity current=find(id); Workout model=WorkoutEntityMapper.toModel(current); apply(model,patch,presence); validatePositions(model); model.setId(id); model.setCreatedAt(current.getCreatedAt()); model.setUpdatedAt(OffsetDateTime.now()); WorkoutEntity replacement=WorkoutEntityMapper.toEntity(model); replacement.setId(id); WorkoutEntity saved=repository.save(replacement); log.info("[WORKOUT] - ACTION: patchWorkout: workoutId: {}",id); return WorkoutEntityMapper.toModel(saved); }
 public void delete(Long id){ WorkoutEntity entity=find(id); repository.delete(entity); log.info("[WORKOUT] - ACTION: deleteWorkout: workoutId: {}",id); }
 private WorkoutEntity find(Long id){ return repository.findById(id).orElseThrow(()->new AppException(AppError.WORKOUT_NOT_FOUND)); }
 private void validatePositions(Workout w){ ensureUnique(w.getSegments().stream().map(WorkoutSegment::getPosition).toList()); ensureUnique(w.getLaps().stream().map(WorkoutLap::getPosition).toList()); ensureUnique(w.getTrackPoints().stream().map(WorkoutTrackPoint::getPosition).toList()); }
 private void ensureUnique(List<Integer> positions){ if(new HashSet<>(positions).size()!=positions.size()) throw new AppException(AppError.DUPLICATE_POSITION); }
 private void apply(Workout t, Workout p, WorkoutPatchPresence x){ if(x.has("workoutDate"))t.setWorkoutDate(p.getWorkoutDate()); if(x.has("name"))t.setName(p.getName()); if(x.has("workoutType"))t.setWorkoutType(p.getWorkoutType()); if(x.has("description"))t.setDescription(p.getDescription()); if(x.has("notes"))t.setNotes(p.getNotes()); if(x.has("distanceMeters"))t.setDistanceMeters(p.getDistanceMeters()); if(x.has("durationSeconds"))t.setDurationSeconds(p.getDurationSeconds()); if(x.has("movingTimeSeconds"))t.setMovingTimeSeconds(p.getMovingTimeSeconds()); if(x.has("averagePaceSecondsPerKm"))t.setAveragePaceSecondsPerKm(p.getAveragePaceSecondsPerKm()); if(x.has("bestPaceSecondsPerKm"))t.setBestPaceSecondsPerKm(p.getBestPaceSecondsPerKm()); if(x.has("averageHeartRate"))t.setAverageHeartRate(p.getAverageHeartRate()); if(x.has("maxHeartRate"))t.setMaxHeartRate(p.getMaxHeartRate()); if(x.has("averageCadence"))t.setAverageCadence(p.getAverageCadence()); if(x.has("maxCadence"))t.setMaxCadence(p.getMaxCadence()); if(x.has("averagePowerWatts"))t.setAveragePowerWatts(p.getAveragePowerWatts()); if(x.has("maxPowerWatts"))t.setMaxPowerWatts(p.getMaxPowerWatts()); if(x.has("elevationGainMeters"))t.setElevationGainMeters(p.getElevationGainMeters()); if(x.has("elevationLossMeters"))t.setElevationLossMeters(p.getElevationLossMeters()); if(x.has("minimumElevationMeters"))t.setMinimumElevationMeters(p.getMinimumElevationMeters()); if(x.has("maximumElevationMeters"))t.setMaximumElevationMeters(p.getMaximumElevationMeters()); if(x.has("calories"))t.setCalories(p.getCalories()); if(x.has("averageStrideLengthMeters"))t.setAverageStrideLengthMeters(p.getAverageStrideLengthMeters()); if(x.has("verticalOscillationCm"))t.setVerticalOscillationCm(p.getVerticalOscillationCm()); if(x.has("groundContactTimeMs"))t.setGroundContactTimeMs(p.getGroundContactTimeMs()); if(x.has("perceivedEffort"))t.setPerceivedEffort(p.getPerceivedEffort()); if(x.has("feeling"))t.setFeeling(p.getFeeling()); if(x.has("completed"))t.setCompleted(p.getCompleted()); if(x.has("temperatureCelsius"))t.setTemperatureCelsius(p.getTemperatureCelsius()); if(x.has("humidityPercent"))t.setHumidityPercent(p.getHumidityPercent()); if(x.has("windSpeedKph"))t.setWindSpeedKph(p.getWindSpeedKph()); if(x.has("weather"))t.setWeather(p.getWeather()); if(x.has("location"))t.setLocation(p.getLocation()); if(x.has("routeName"))t.setRouteName(p.getRouteName()); if(x.has("source"))t.setSource(p.getSource()); if(x.has("externalActivityId"))t.setExternalActivityId(p.getExternalActivityId()); if(x.has("shoeId"))t.setShoeId(p.getShoeId()); if(x.has("segments"))t.setSegments(p.getSegments()==null?new ArrayList<>():p.getSegments()); if(x.has("laps"))t.setLaps(p.getLaps()==null?new ArrayList<>():p.getLaps()); if(x.has("trackPoints"))t.setTrackPoints(p.getTrackPoints()==null?new ArrayList<>():p.getTrackPoints()); }
}
